### ISSUE TITLE
Error in plotMetric with GMM model

### ISSUE THREAD

**Issue by hichew22** [philips-software/latrend#137]
Hello,

I am using latrend to cluster using LLPA/finite Gaussian mixture modeling. After fitting my data for a range of 2-5 clusters as so:
gmm_method <- lcMethodMclustLLPA(response = "y", nClusters = 2, nbRedrawing = 1)
gmm_methods <- lcMethods(gmm_method, nClusters = 2:5)

and fitting the list of lcMethod objects with the latrendBatch function to return a list of lcModel objects:
gmm_models <- latrendBatch(gmm_methods, data = df)
gmm_models

I attempt to compare the cluster metrics between the 2-5 clusters:
metric(gmm_models, c("WMAE", "BIC"))

However, when I run this code:
plotMetric(gmm_models, c("Dunn", "ASW", "WMAE", "WRSS", "BIC", "estimationTime"))

I receive the error:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘getShortName’ for signature ‘"logical"’

Would you be able to help me with this?

Thank you!

**Comment by niekdt** [comment]
Hi, thanks for the clear reproducible report. I was able to reproduce the problem and it should now be fixed. Install the latest commit from master to get the fix.

**Comment by hichew22** [comment]
Hello, can you let me know what it means to "install the latest commit from master?" Thank you very much!

**Comment by hichew22** [comment]
Hello,

I ran the following command to install the commit: 
remotes::install_github('philips-software/latrend', ref = remotes::github_release())

However, when I run that line of code plotMetric(gmm_models, c("Dunn", "ASW", "WMAE", "WRSS", "BIC", "estimationTime")), I still get the same error. Could you help me look into this?

Thank you!

**Comment by hichew22** [comment]
When I try plotting the clusters as so:
gmm_model_4 <- subset(gmm_models, nClusters == 4, drop = TRUE)

I also get the same error: Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘getShortName’ for signature ‘"logical"’

**Comment by niekdt** [comment]
I think `remotes::install_github('philips-software/latrend')` will install the latest commit. It should fix both errors.

**Comment by hichew22** [comment]
I ran that command and those functions work now, thank you very much!
